server:
  port: 3000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xiaomi?useUnicode=true&useSSL=true&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  redis:
    host: localhost
  rabbitmq:
    host: localhost
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true